### ISSUE TITLE
When out is subdir, gotag can't find go file

### ISSUE THREAD

**Issue by moxianfeng** [srikrsna/protoc-gen-gotag#25]
buf.gen.yaml 

```
version: v1
plugins:
  - name: go
    out: golang
    opt:
      - paths=source_relative
  - name: gotag
    out: golang
    opt:
      - paths=source_relative
  - name: go-grpc
    out: golang
    opt:
      - paths=source_relative
  - name: grpc-gateway
    out: golang
    opt:
      - paths=source_relative
      - grpc_api_configuration=buf.yaml
  - name: openapiv2
    out: openapiv2
    opt:
      - use_go_templates=true
  - name: validate
    out: golang
    opt:
      - lang=go
      - paths=source_relative
```

and execute

buf generate

all file be generated, bug tag not inject, and an error occurred.

```
[error] [gotag]: open model.pb.go: no such file or directory
Failure: plugin gotag: exit status 1.
```

when i try modify output path to `.`
everything is ok.

**Comment by moxianfeng** [comment]
Check the code, use option outdir indicate path, buf's out option not work for protoc-gen-gotag. so should use buf config like this:

```
- name: gotag
    out: golang
    opt:
      - outdir=golang
      - paths=source_relative
```
