### ISSUE TITLE
Can't find pb file error

### ISSUE THREAD

**Issue by cmzz** [srikrsna/protoc-gen-gotag#27]
buf.gen.yaml

```
version: v1
plugins:
  - name: go
    out: .
    opt:
      - paths=source_relative
  - name: gotag
    out: .
    opt:
      - outdir=.
      - paths=source_relative
```

file trees:
```
proto/
---   buf.gen.yaml
---   buf.lock
---   buf.yaml
---   eventmsg.proto
```

got error:

[error] [gotag]: open eventmsg.pb.go: no such file or directory
Failure: failed to generate plugins concurrently: failed to execute plugins concurrently: failed to generate: exit status 1
