### ISSUE TITLE
Remove imports for other language

### ISSUE THREAD

**Issue by nwosuudoka** [srikrsna/protoc-gen-gotag#30]
So I have generated protobuf messages for go as well as nodejs 

But in the generated typescript file, I have the tagger imports 

How can I exclude this from that file?

```
// package: cryptocurrency.v1
// file: cryptocurrency/v1/cryptocurrency.proto

/* tslint:disable */
/* eslint-disable */

import * as jspb from "google-protobuf";
import * as tagger_tagger_pb from "../../tagger/tagger_pb";  <--- THIS
```

buf.yaml file
```
version: v1
name: buf.build/nwosuudoka/ssschema
deps:
  - buf.build/srikrsna/protoc-gen-gotag
lint:
  ignore:
    - google
  use:
    - DEFAULT
    - COMMENTS
    - FILE_LOWER_SNAKE_CASE
  rpc_allow_google_protobuf_empty_requests: true
  rpc_allow_google_protobuf_empty_responses: true

breaking:
  ignore_unstable_packages: true
  use:
    - WIRE
```

buf.gen.yaml

```
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/nwosuudoka/ssschema
    except:
      # - buf.build/googleapis/googleapis
      # - buf.build/envoyproxy/protoc-gen-validate
      - buf.build/srikrsna/protoc-gen-gotag

plugins:
  - name: go
    out: go
    opt: paths=source_relative
  - name: go-grpc
    out: go
    opt: paths=source_relative
  - name: ts
    out: typescript
    path: protoc-gen-ts
    # path: node_modules/.bin/protoc-gen-ts_proto
```
