### ISSUE TITLE
Option to consistently sort tags

### ISSUE THREAD

**Issue by jgkawell** [srikrsna/protoc-gen-gotag#51]
Often I run into the case mentioned in #38 where I will regenerated a file and end up with changes because the sorting of the tags changes randomly on each compilation. This causes issues in automation because changes are being detected in generated files when no functional change has actually been made. Here's an example of the git diff:

![image](https://github.com/srikrsna/protoc-gen-gotag/assets/27896502/64cd9bee-57ba-4651-8d8e-4e14e5c68752)

I'm  seeing this issue on the latest stable version v1.0.1.

**Comment by jgkawell** [comment]
Not really sure if this is a bug or a feature request. I'm happy to implement this if there's interest and you can point me in the right direction.

**Comment by ucpr** [comment]
Hi @jgkawell,

Thank you for the report. I'll take a look at it shortly.

How often does this problem occur?

**Comment by jgkawell** [comment]
@ucpr Sorry for the late reply. This happens every time I generate files using the plugin. For example, I might generate the files once and get one ordering of tags and then generate the files immediately after and get a different ordering. The order seems to be completely random.

**Comment by ucpr** [comment]
@jgkawell 

I attempted to reproduce the problem in my environment, but I was unable to do so. To help me investigate further, could you please provide the minimal configuration required to reproduce the issue?

**Comment by joaopedrovbs** [comment]
I also have the same problem! It always changes the order for the auto-generated tags. This is what I have in the `buf.gen.tag.yaml` :

``` YAML
version: v1
plugins:
  - plugin: gotag
    out: .
    opt: paths=source_relative,outdir=gen/go,auto=json-as-lower_camel_case+bson-as-lower_camel_case+db-as-snake_case

**Comment by jgkawell** [comment]
Okay I've got a repeatable example for you:
- buf version = 1.35.1
- protoc-gen-go version = 1.34.2
- protoc-gen-gotag version =  1.0.1

`buf.yaml`
```yaml
version: v1
```

`buf.gen.go.yaml`
```yaml
version: v1
plugins:
  - name: go
    out: .
    opt:
      - paths=source_relative
```

`buf.gen.gotag.yaml`
```yaml
version: v1
plugins:
  - name: gotag
    out: .
    opt:
      - outdir=.
      - paths=source_relative
      - xxx=pg+"-" bun+"-" json+"-" yaml+"-" csv+"-"
      - auto=pg-as-lower_snake+bun-as-lower_snake+yaml-as-lower_snake+csv-as-lower_snake+json-as-lower_snake
```

`service.proto`
```proto
syntax = "proto3";

package v1;

option go_package = "github.com/example/example";

service EchoService {
    rpc Speak(SpeakRequest) returns(SpeakResponse) {}
}

message SpeakRequest {
    string input = 1;
}

message SpeakResponse {
    string output = 2;
}
```

Running the below command over and over will randomly change the position of the tags:

```shell
buf generate --template buf.gen.go.yaml && buf generate --template buf.gen.gotag.yaml
```
