### ISSUE TITLE
can we specify where the pb.go file is or reuse the output path

### ISSUE THREAD

**Issue by sebglon** [srikrsna/protoc-gen-gotag#9]
I use the uber/prototoolto generate all my grpc client. but gotag not find the genrated *.pb.go files.

is it possible to specify the input folder?

**Comment by srikrsna** [comment]
I don't think the problem is in finding the output. My guess is that prototool runs all plugins in a single command. This plugin needs generated files and hence cannot be used in the same step as other protoc plugins. It has to be run separately i.e. after prototool. See #6

**Comment by sebglon** [comment]
No prototool use one cmd by plugin. But the gotag not found generated file by go plugin because the generated files are on folder.

**Comment by srikrsna** [comment]
@sebglon Is there an update on this?

**Comment by brownoxford** [comment]
I'm running into this a well. My use case is that I use [prototool](https://github.com/uber/prototool), which allows you to configure plugin arguments that get run in order, and I am currently working around this issue by specifying that `protoc-gen-go` use `.` as an output folder, then having `protoc-gen-gotag` use my actual desired location as output. This two-step process leaves me with generated `.pb.go` files in my working folder, but I just `.gitignore` them.

Ideally, we would be able to specify the root folder where `protoc-gen-gotag` looks for `.pb.go` files so that they can be edited in-place without the intermediate step.

**Comment by Dasio** [comment]
I'm having the same issue:
I got proto file in api/svc and generated file in pkg/svc, running command within root folder
```
protoc -Iapi/svc \
		-Iapi \
		--go_out=plugins=grpc:pkg/api \
		--grpc-gateway_out=logtostderr=true:pkg/api \
		svc.proto
protoc -Iapi/svc \
	-Iapi \
	--gotag_out=xxx="pg+\"-\"":pkg/api \
	svc.proto
```
I'm getting into `[error] [gotag]: open svc.pb.go: no such file or directory`
My workaround is after first protoc copy svc.pb.go from pkg/api to root, run second command with gotagout and rm it.

gotagout correctly  updates svc.pb.go in pkg/api and leave .pb.go in root folder untouched

**Comment by srikrsna** [comment]
I'm having a hard time trying to replicate the issue. I've pushed a new branch prototool-example. I am using prototool to generate the example and it is working for me.

I am running the command `prototool generate ./example` in the root. 

@Dasio @brownoxford Can you please take a look and help me replicate?

**Comment by brownoxford** [comment]
Looks like you need a `prototool.yaml` config file in the root, this is the relevant parts of one that I use:
```yaml
protoc:
  version: 3.10.0
lint:
  group: google
generate:
  go_options:
    import_path: .
  plugins:
    - name: go
      type: go
      output: . # `gotag` plugin looks in current folder
    - name: gotag
      flags: xxx=bson+"-" # Omit internal fields from bson
      output: output/
```
Notice that I configure the output of `protoc-gen-to` to be the current folder, then I run `protoc-gen-gotag` and use the `output` folder that I really want (I output different languages to different places in a monorepo). The end result is that `./example/example.pb.go` is created without the tags, then `./output/example/example.pb.go` is created with the tags. This is a functional work-around, but it would be nice if we didn't have those un-tagged files laying around in `./example` (I .gitignore mine for this workaround).

Note that there is a second issue here having to do with prototool itself - the order of operations is not right so you have to run `prototool` twice to ensure that `protoc-gen-gotag` is using the right source.

**Comment by srikrsna** [comment]
> Looks like you need a `prototool.yaml` config file in the root, this is the relevant parts of one that I use:

But I do have one in the root in prototool-example branch, this is how it looks

```yaml
protoc:
  version: 3.8.0
# Code generation directives.
generate:
  # The list of plugins.
  go_options:
    # The base import path. This should be the go path of the prototool.yaml file.
    # This is required if you have any go plugins.
    import_path: github.com/srikrsna/protoc-gen-gotag
  plugins:
    - name: go
      type: go
      output: .
    - name: gotag
      type: go
      output: .
      flags: 'xxx=graphql+"-" bson+"-"'

```

Using the same output folder as go plugin works for me.

**Comment by brownoxford** [comment]
Ah, sorry, I must have messed up after checkout. In any case, everything else stands - if you want to have your output in a different folder, you are required to add an extra step to your build chain. This step is either deleting/ignoring the .go.pb files in `./*`, or manually moving them to the final desired location.

If there was a way to tell gotag where to look for the input files instead of defaulting to `.`, this additional step could be omitted.

**Comment by srikrsna** [comment]
> If there was a way to tell gotag where to look for the input files instead of defaulting to `.`, this additional step could be omitted.

This is what is unclear for me, it does not default to `.` it looks in the output folder that was provided.

If I am missing something, please provide steps to replicate the error.

**Comment by yinzara** [comment]
Same issue here.  Though I think I have simpler reproduction steps.

If I try to output to a subfolder of the current folder, that's where the issue happens.
Let's say my protos are in:
/proto

and my project in in "/foo/bar" (where prototool.yaml) is and my "output" directory is "pkg"

If I'm in the "/foo/bar" directory and I execute
```bash
protoc -I ../../proto -I ./pkg --gotag_out=./pkg ../proto/myprotofile.proto
```
I get the error:
`[error] [gotag]: open myprotofile.pb.go: no such file or directory`

However if I run the following command from "/foo/bar/pkg" it executes and functions normally:
```bash
protoc -I ../../../proto -I . --gotag_out=. ../../proto/myprotofile.proto
```

**Comment by yinzara** [comment]
And reading through the code I now know the issue.

module/tagger.go line 47
```
gfname := m.Context.OutputPath(f).SetExt(".go").String()
```
m.Context.OutputPath's documentation states:
// OutputPath returns the output path relative to the plugin's output destination

That means that the "gfname" is actually a relative path to the plugins output destination, not the absolutely path.  

Even the "m.BuildContext.OutputPath()" only returns a relative reference.

Unfortunately it seems that the CodeGeneratorRequest proto does not include any way of getting the actual output directory specified as part of the protoc command.

This means that if we want this plugin to work, we're going to have to allow passing a generator parameter (like the xxx). I'm guessing "outdir" is probably the best.  That would allow us to specify an output directory to be passed into the plugin.

**Comment by yinzara** [comment]
When PR #13 is merged, the following prototool.yaml works perfectly.

```yaml
generate:
  plugins:
    - name: go
      flags: plugins=grpc
      output: ./pkg

    - name: gotag
      output: ./pkg
      flags: outdir=./pkg
```
